version: '3.1'
services:
  app:
    container_name: spring-leverx
    image: spring-leverx
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=postgres
      - POSTGRES_DB=leverx
  redis:
    image: redis
    ports:
      - "6379:6379"